server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://j10b107.p.ssafy.io:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  cors:
    # CORS 구성
    allowed-origins: http://localhost:8000
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers: Authorization, Content-Type
    max-age: 3600

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  profiles:
    include: oauth, jwt

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    root: DEBUG
