server:
  port: 8086

spring:
  cloud:
    config:
      name: teddy
      profile: user


  application:
    name: user-service

  config:
    import: optional:configserver:http://config:8763

#  datasource:
#    url: jdbc:mysql://mysql:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
#    username: root
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    generate-ddl: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

#  profiles:
#    include: oauth, jwt
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://discovery:8761/eureka

#logging:
#  level:
#    root: DEBUG
