spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 443022535247-v1gmo6vrei8n1q7bfv6ahfvfo2fj8fs2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/youtube.readonly