server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://j10b107.p.ssafy.io:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  cors:
    # CORS 구성
    allowed-origins: http://localhost:8000
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers: Authorization, Content-Type
    max-age: 3600

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  profiles:
    include: oauth

#               강제로 scope를 email과 profile로 등록한 이유는?
# scope의 기본값은 openid, email, profile
# 하지만 openid라는 scope가 있으면 OpenId Provider로 인식
# 그렇게 되면 OpenId Provider인 서비스(구글)와 그렇지 않은 서비스(네이버, 카카오 등)로 나눠서 각각 OAuth2Service를 만들어야 함
# 하나의 OAuth2Service를 사용하기 위해 일부러 openid scope를 빼고 등록

#  application-oauth.yml을 따로 만들 경우 주석 해제
#  profiles:
#    include: oauth

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    root: DEBUG
