spring:
  security:
    oauth2:
      client:
        registration:
          google:
<<<<<<< HEAD
            client-id: 443022535247-v1gmo6vrei8n1q7bfv6ahfvfo2fj8fs2.apps.googleusercontent.com
            client-secret: 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
=======
            client-id: 198743836956-ls6nit1j3mee99nui7h95tud1vfgoean.apps.googleusercontent.com
            client-secret: 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
>>>>>>> cb3c1d46ad2d9fcd3c4d961d31f3b4f415c78b1f
            redirect-uri: https://j10b107.p.ssafy.io:8086/login/oauth2/code/google
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/youtube.readonly

#               강제로 scope를 email과 profile로 등록한 이유는?
# scope의 기본값은 openid, email, profile
# 하지만 openid라는 scope가 있으면 OpenId Provider로 인식
# 그렇게 되면 OpenId Provider인 서비스(구글)와 그렇지 않은 서비스(네이버, 카카오 등)로 나눠서 각각 OAuth2Service를 만들어야 함
# 하나의 OAuth2Service를 사용하기 위해 일부러 openid scope를 빼고 등록