server:
  port: 8086

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://j10b107.p.ssafy.io:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Drivergit 

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

  profiles:
    include: oauth, jwt

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j10b107.p.ssafy.io:8761/eureka

#logging:
#  level:
#    root: DEBUG
