server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allow-credentials: true
            allowedHeaders: '*'
            exposedHeaders: '*'
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

        - id: word-service
          uri: lb://WORD-SERVICE
          predicates:
            - Path=/word-service/**

        - id: video-service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/video-service/**

        - id: python-service
          uri: lb://PYTHON-SERVICE
          predicates:
            - Path=/data-service/**
          filters:
            - RewritePath=/data-service/(?<segment>.*), /$\{segment}

        - id: swagger-ui
          uri: lb://swagger-service
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/(?<path>.*), /$\\{path}
