server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://discovery:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allow-credentials: true
            allowedHeaders: '*'
            exposedHeaders: '*'
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/**
          filters:
            - RewritePath=/api/user-service/(?<segment>.*), /user-service/${segment}

        - id: word-service
          uri: lb://WORD-SERVICE
          predicates:
            - Path=/api/word-service/**
          filters:
            - RewritePath=/api/word-service/(?<segment>.*), /word-service/${segment}

        - id: video-service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/api/video-service/**
          filters:
            - RewritePath=/api/video-service/(?<segment>.*), /video-service/$\{segment}

        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/api/test-service/**
          filters:
            - RewritePath=/api/test-service/(?<segment>.*), /test-service/$\{segment}

        - id: script-service
          uri: lb://SCRIPT-SERVICE
          predicates:
            - Path=/api/script-service/**
          filters:
            - RewritePath=/api/script-service/(?<segment>.*), /script-service/${segment}

        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/category-service/**
          filters:
            - RewritePath=/api/category-service/(?<segment>.*), /category-service/${segment}

        - id: python-service
          uri: lb://PYTHON-SERVICE
          predicates:
            - Path=/data-service/**
          filters:
            - RewritePath=/data-service/(?<segment>.*), /$\{segment}

        - id: swagger-ui
          uri: lb://swagger-service
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/(?<path>.*), /$\\{path}
