server:
    port: 8764

spring:
    cloud:
        config:
            name: cloud
            profile: user

    application:
        name: user-service

    config:
        import: optional:configserver:http://config:8763

    # rabbitmq
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: ssafy
        password: b107

    # sql connect
    datasource:
        url: jdbc:mysql://mysql:3306/test?useSSL=false&serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
        username: root
        password: ssafy
        driver-class-name: com.mysql.cj.jdbc.Driver

    #  datasource:
    ##   h2 db
    #    driver-class-name: com.mysql.jdbc.Driver
    ##   db url
    #    url:
    ##   db name
    #    username: sa
    ##   db password
    #    password:
    #
    #  h2:
    #    console:
    ##     H2 console 사용 여부(사용 시 해당 port에서 접근)
    #      enabled: true
    #      settings:
    ##       외부 접근 허용
    #        web-allow-others: true
    ##     H2 console path정보 port/h2-console 시 콘솔로 접근함
    #      path: /h2-console

    # jpa
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8InnoDBDialect
#eureka
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#
#logging:
#  level:
#    com.ssafy.userservice.client: DEBUG
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
#
#management:
#  observations:
#    annotations:
#      enabled: true
#  tracing:
#    sampling:
#      probability: 1.0
#    propagation:
#      consume: B3
#      produce: B3_MULTI
#  zipkin:
#    tracing:
#
#      endpoint: 'http://localhost:9411/api/v2/spans'
#  endpoints:
#    web:
#      exposure:
#        include: refresh, health, beans, httpexchanges,  busrefresh, info, metrics, prometheus
