server:
  port: 8084

spring:
  application:
    name: test-service
  data:
    mongodb:
      uri: mongodb://ssafy:b107@j10b107.p.ssafy.io:27017/teddybear?authSource=admin
  datasource:
    url: jdbc:mysql://j10b107.p.ssafy.io:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery/eureka