server:
  port: 8084

spring:
  application:
    name: test-service
  data:
    mongodb:
      uri: mongodb://ssafy:b107@j10b107.p.ssafy.io:27017/teddybear?authSource=admin

eureka:
  instance:
    #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka